### ISSUE TITLE
error using globally with nvm installed node, global version expected to find node executable in /usr/local/bin/node

### ISSUE THREAD

**Issue by victorkane** [vot/xkpasswd-node#2]
Error:

```
$ xkpasswd
bash: /home/victorkane/.nvm/versions/node/v4.4.5/bin/xkpasswd: /usr/local/bin/node: bad interpreter: No such file or director
```

Same with alias `xkp`

Workaround: 

```
$ sudo ln -s /home/victorkane/.nvm/versions/node/v4.4.5/bin/node /usr/local/bin/node
```

**Comment by vot** [comment]
Hi Victor,

Thanks for raising an issue, sorry for the delay.
I haven't actually tested this with nvm but rather with plain node setup. I suppose the nvm's bindings may be broken for some reason on your machine but I can't guarantee that's it.

Can you check if some other globally installed package that creates an alias causes the same problem?
You can try my other package with `npm install -g npm-toolkit` and then see what `nt status` returns (if anything at all), that might be helpful in debugging. I would expect to see the correct version of node interpreter listed there. Is that the same as the output of `node --version`?

Try following where the relevant aliases lead (`which node; which xkp`) and list the contents of the containing folder - most likely /usr/local/bin/node and /usr/local/bin/xkp. Follow the symlinks to see which versions they resolve to.

Do you have any other globally installed npm packages that you can confirm as working? If so, where do the symlinks in your bin folder point to?

I know of cases where uninstalling all versions of node and nvm from the machine and then doing a clean install helped with this kind of issues. Is that an option for you?

**Comment by vot** [comment]
Hi @victorkane, Since you didn't reply in over two months I'm assuming you're no longer experiencing the issue? Unless you're still having this problem I'll be closing this issue as it seems to be with node setup rather than with xkp.
