### ISSUE TITLE
After installation, errors with "The system cannot find the path specified."

### ISSUE THREAD

**Issue by sumo300** [vot/xkpasswd-node#3]
Running either xkp or xkpasswd throws same error:

The system cannot find the path specified.

Other NPM modules work/run just fine.

Platform: Windows 7 Enterprise x64

**Comment by vot** [comment]
Hi, it was just an incorrect shebang line in cli.js.
This is now fixed and version 0.0.9 has been published.

Let me know if it works fine for you.

**Comment by sumo300** [comment]
Yes, works now!
